// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package runner

import (
	"artbycode.id/go-app/internal/api"
	"artbycode.id/go-app/internal/config"
	"artbycode.id/go-app/internal/services/auth"
	"artbycode.id/go-app/internal/services/auth/authimpl"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeRunnerServer() *RunnerServer {
	configService := config.NewConfigService()
	userRepositoryImpl := authimpl.NewUserRepositoryImpl()
	authServiceImpl := authimpl.NewAuthServiceImpl(userRepositoryImpl)
	apiService := api.NewApiService(configService, authServiceImpl)
	runnerServer := NewRunnerServer(apiService, configService)
	return runnerServer
}

// wire.go:

var wireSetService = wire.NewSet(
	NewRunnerServer, api.NewApiService, config.NewConfigService, authimpl.NewUserRepositoryImpl, wire.Bind(new(auth.UserRepository), new(*authimpl.UserRepositoryImpl)), authimpl.NewAuthServiceImpl, wire.Bind(new(auth.AuthService), new(*authimpl.AuthServiceImpl)),
)
